# -*- coding: utf-8 -*-
"""APF

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L3s0XZDlSMXZlc3vNHvyuQQ8zYvV-T2o

<div class="markdown-google-sans">

## 其他資源

### 在 Colab 中使用筆記本

</div>

- [Colab 總覽](/notebooks/basic_features_overview.ipynb)
- [Markdown 指南](/notebooks/markdown_guide.ipynb)
- [匯入程式庫及安裝依附元件](/notebooks/snippets/importing_libraries.ipynb)
- [儲存和載入 GitHub 中的筆記本](https://colab.research.google.com/github/googlecolab/colabtools/blob/main/notebooks/colab-github-demo.ipynb)
- [互動式表單](/notebooks/forms.ipynb)
- [互動式小工具](/notebooks/widgets.ipynb)

<div class="markdown-google-sans">

<a name="working-with-data"></a>
### 處理資料
</div>

- [載入資料：雲端硬碟、試算表及 Google Cloud Storage](/notebooks/io.ipynb)
- [圖表：將資料視覺化](/notebooks/charts.ipynb)
- [開始使用 BigQuery](/notebooks/bigquery.ipynb)

<div class="markdown-google-sans">

### 機器學習

<div>

以下是一些與機器學習相關的筆記本，包括 Google 線上機器學習課程。詳情請參閱<a href="https://developers.google.com/machine-learning/crash-course/">完整課程網站</a>。
- [Pandas DataFrame 簡介](https://colab.research.google.com/github/google/eng-edu/blob/main/ml/cc/exercises/pandas_dataframe_ultraquick_tutorial.ipynb)
- [加快 pandas 速度的 RAPIDS cuDF 簡介](https://nvda.ws/rapids-cudf)
- [開始使用 cuML 的加速器模式](https://colab.research.google.com/github/rapidsai-community/showcase/blob/main/getting_started_tutorials/cuml_sklearn_colab_demo.ipynb)

<div class="markdown-google-sans">

<a name="using-accelerated-hardware"></a>
### 使用加速硬體
</div>

- [運用 Flax NNX API 訓練 CNN 分類 MNIST 資料集中的手寫數字](https://colab.research.google.com/github/google/flax/blob/main/docs_nnx/mnist_tutorial.ipynb)
- [運用 JAX 訓練 Vision Transformer &#40;ViT&#41; 分類圖像](https://colab.research.google.com/github/jax-ml/jax-ai-stack/blob/main/docs/source/JAX_Vision_transformer.ipynb)
- [運用 JAX 打造可分類文字的 Transformer 語言模型](https://colab.research.google.com/github/jax-ml/jax-ai-stack/blob/main/docs/source/JAX_transformer_text_classification.ipynb)

<div class="markdown-google-sans">

<a name="machine-learning-examples"></a>

### 主要範例

</div>

- <a href="https://docs.jaxstack.ai/en/latest/JAX_for_LLM_pretraining.html">運用 JAX AI Stack 訓練 miniGPT 語言模型</a>
- <a href="https://github.com/google/tunix/blob/main/examples/qlora_gemma.ipynb">運用 Tunix 進行 LLM 的 LoRA/QLoRA 微調</a>
- <a href="https://keras.io/examples/keras_recipes/parameter_efficient_finetuning_of_gemma_with_lora_and_qlora/">運用 LoRA 和 QLoRA 進行 Gemma 的高效參數微調</a>
- <a href="https://keras.io/keras_hub/guides/hugging_face_keras_integration/">載入 Hugging Face Transformer 查核點</a>
- <a href="https://keras.io/guides/int8_quantization_in_keras/">Keras 的 8 位元整數量化</a>
- <a href="https://keras.io/examples/keras_recipes/float8_training_and_inference_with_transformer/">運用簡易 Transformer 模型進行 Float8 訓練及推論</a>
- <a href="https://keras.io/keras_hub/guides/transformer_pretraining/">運用 KerasHub 從頭開始預先訓練 Transformer</a>
- <a href="https://keras.io/examples/vision/mnist_convnet/">簡易 MNIST 卷積神經網路</a>
- <a href="https://keras.io/examples/vision/image_classification_from_scratch/">運用 Keras 3 從頭開始分類圖像</a>
- <a href="https://keras.io/keras_hub/guides/classification_with_keras_hub/">運用 KerasHub 分類圖像</a>
"""

import numpy as np
import matplotlib.pyplot as plt

# ====== 參數（依論文可調） ======
ka = 1.0          # 吸引力係數
kr = 1.0          # 排斥力係數
Q  = 2.0          # 障礙影響半徑

goal = np.array([8.0, 8.0])
obstacles = [
    np.array([4.0, 4.0]),
    np.array([6.0, 2.0])
]

# ====== 建立空間 ======
x = np.linspace(0, 10, 200)
y = np.linspace(0, 10, 200)
X, Y = np.meshgrid(x, y)
U = np.zeros_like(X)

# ====== 吸引勢場 ======
U_att = 0.5 * ka * ((X - goal[0])**2 + (Y - goal[1])**2)

# ====== 排斥勢場 ======
U_rep = np.zeros_like(U)

for obs in obstacles:
    d = np.sqrt((X - obs[0])**2 + (Y - obs[1])**2)
    mask = d <= Q
    U_rep[mask] += 0.5 * kr * (1/d[mask] - 1/Q)**2

# ====== 總勢場 ======
U = U_att + U_rep

# ====== 繪圖 ======
plt.figure(figsize=(7,6))
plt.contourf(X, Y, U, levels=50, cmap="jet")
plt.colorbar(label="Potential U")

plt.scatter(goal[0], goal[1], c='white', marker='*', s=150, label="Goal")
for obs in obstacles:
    plt.scatter(obs[0], obs[1], c='black', s=100, label="Obstacle")

plt.title("APF Potential Field (based on paper Section 4-2)")
plt.xlabel("X")
plt.ylabel("Y")
plt.legend(loc="upper right")
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# =============================
# 1. 參數設定（論文風格）
# =============================
ka = 0.1        # 吸引力係數
kr = 80.0        # 排斥力係數
Q  = 50.0        # 障礙影響距離

goal = np.array([90, 90])

# =============================
# 2. 障礙物（依圖片手動近似）
# 格式：(x, y, radius)
# =============================
obstacles = [
    (30, 40, 12),
    (55, 35, 10),
    (70, 60, 14),
    (50, 70, 10),
    (15, 35, 6),
    (60, 25, 6),
    (95, 25, 6)
]

# =============================
# 3. 建立空間網格
# =============================
x = np.linspace(0, 100, 300)
y = np.linspace(0, 100, 300)
X, Y = np.meshgrid(x, y)
U = np.zeros_like(X)

# =============================
# 4. 吸引勢場
# =============================
U_att = 0.5 * ka * ((X - goal[0])**2 + (Y - goal[1])**2)

# =============================
# 5. 排斥勢場
# =============================
U_rep = np.zeros_like(U)

for ox, oy, r in obstacles:
    d = np.sqrt((X - ox)**2 + (Y - oy)**2) - r
    mask = d <= Q
    d_safe = np.maximum(d, 1e-3)
    U_rep[mask] += 0.5 * kr * (1/d_safe[mask] - 1/Q)**2

# 勢能總和
U = U_att + U_rep

# === 關鍵：對數視覺化 ===
U_vis = np.log(U + 1)

plt.figure(figsize=(7,7))
plt.contourf(X, Y, U_vis, levels=80, cmap="jet")
plt.colorbar(label="log(Potential U)")

plt.scatter(goal[0], goal[1], c="lime", s=120, marker="*", label="Goal")

for ox, oy, r in obstacles:
    circle = plt.Circle((ox, oy), r, color='green', alpha=0.5)
    plt.gca().add_patch(circle)

plt.title("APF Potential Field (Log-scaled Visualization)")
plt.xlim(0,100)
plt.ylim(0,100)
plt.grid(True)
plt.legend()
plt.show()

"""# 新增區段"""

import numpy as np
import matplotlib.pyplot as plt

np.random.seed(0)

start = np.array([10, 10])
goal  = np.array([90, 90])

obstacles = [
    (60, 20, 12),
    (25, 40, 10),
    (80, 40, 10),
    (20, 60, 14),
    (40, 30, 10),
]

N = 1000

import numpy as np
import matplotlib.pyplot as plt

class Node:
    def __init__(self, p):
        self.p = np.array(p)
        self.parent = None
        self.cost = 0.0

def dist(a, b):
    return np.linalg.norm(a - b)

def collision(p, obstacles):
    for ox, oy, r in obstacles:
        if dist(p, np.array([ox, oy])) <= r:
            return True
    return False

rrt_nodes = np.random.uniform(0, 100, (N, 2))

def sample_in_ellipse(start, goal, c_max):
    c = (start + goal) / 2
    a = c_max / 2
    d = dist(start, goal) / 2
    b = np.sqrt(a*a - d*d)

    t = np.random.uniform(0, 2*np.pi)
    r = np.sqrt(np.random.rand())

    x = r * a * np.cos(t)
    y = r * b * np.sin(t)

    ang = np.arctan2(goal[1]-start[1], goal[0]-start[0])
    R = np.array([[np.cos(ang), -np.sin(ang)],
                  [np.sin(ang),  np.cos(ang)]])

    return c + R @ np.array([x, y])

def apf_bias(p, goal, obstacles):
    p = np.array(p, dtype=float)
    goal = np.array(goal, dtype=float)
    F = goal - p
    for ox, oy, r in obstacles:
        d = dist(p, np.array([ox, oy])) - r
        if d < 20:
            F -= 30 * (p - np.array([ox, oy])) / (d*d + 1e-3)
    return F / (np.linalg.norm(F) + 1e-6)

import time

def rrt_star(mode):
    t0 = time.time()

    nodes = [Node(start)]
    samples = []
    goal_node = None

    for _ in range(800):
        # --- sampling ---
        if mode == "rrt":
            x_rand = np.random.uniform(0, 100, 2)
        else:
            x_rand = sample_in_ellipse(start, goal, 140)

        samples.append(x_rand)

        nearest = min(nodes, key=lambda n: dist(n.p, x_rand))

        direction = x_rand - nearest.p
        if mode == "apf":
            direction += 10 * apf_bias(nearest.p, goal, obstacles)

        direction /= (np.linalg.norm(direction) + 1e-6)
        x_new = nearest.p + 3 * direction

        if collision(x_new, obstacles):
            continue

        new = Node(x_new)
        new.parent = nearest
        new.cost = nearest.cost + dist(nearest.p, x_new)
        nodes.append(new)

        if dist(x_new, goal) < 3:
            goal_node = Node(goal)
            goal_node.parent = new
            nodes.append(goal_node)
            break

    t1 = time.time()

    return {
        "nodes": nodes,
        "samples": samples,
        "goal": goal_node,
        "time": t1 - t0
    }

start = np.array([10, 10])
goal  = np.array([90, 90])

obstacles = [ (95, 25, 5), (10, 75, 5),
 (65,25,5), (25,95,5), (15, 35, 5),(30, 40, 10),(50, 32.5, 7.5),(50, 67.5, 7.5),(70, 60, 10), ]

results = {
    "RRT*": rrt_star("rrt"),
    "Informed-RRT*": rrt_star("informed"),
    "APF-Informed-RRT*": rrt_star("apf")
}

def path_length(goal_node):
    if goal_node is None:
        return np.inf

    length = 0.0
    n = goal_node
    while n.parent:
        length += dist(n.p, n.parent.p)
        n = n.parent
    return length

def path_length(goal_node):
    if goal_node is None:
        return np.inf

    length = 0.0
    n = goal_node
    while n.parent:
        length += dist(n.p, n.parent.p)
        n = n.parent
    return length

methods = {
    "RRT*": "rrt",
    "Informed-RRT*": "informed",
    "APF-Informed-RRT*": "apf"
}

stats = {}

for name, mode in methods.items():
    result = rrt_star(mode)
    stats[name] = {
        "node_count": len(result["nodes"]),
        "path_length": path_length(result["goal"]),
        "time": result["time"]
    }

fig, axs = plt.subplots(1, 3, figsize=(18,6))

for ax, (title, result) in zip(axs, results.items()):
    nodes = result["nodes"]
    samples = np.array(result["samples"])
    goal_node = result["goal"]

    # ---- samples ----
    ax.scatter(samples[:,0], samples[:,1], s=2, alpha=0.3)

    # ---- tree edges ----
    for n in nodes:
        if n.parent:
            ax.plot(
                [n.p[0], n.parent.p[0]],
                [n.p[1], n.parent.p[1]],
                color="gray",
                linewidth=0.4
            )

    # ---- final path ----
    if goal_node:
        path = []
        n = goal_node
        while n:
            path.append(n.p)
            n = n.parent
        path = np.array(path)
        ax.plot(path[:,0], path[:,1], 'r', linewidth=3)

    # ---- obstacles ----
    for ox, oy, r in obstacles:
        ax.add_patch(plt.Circle((ox, oy), r, color='green', alpha=0.4))

    # ---- start / goal ----
    ax.scatter(start[0], start[1], c='red', s=60, label="Start")
    ax.scatter(goal[0], goal[1], c='lime', s=60, label="Goal")

    ax.set_title(title)
    ax.set_xlim(0,100)
    ax.set_ylim(0,100)
    ax.grid(True)

plt.tight_layout()
plt.show()

methods = ["RRT*", "Informed-RRT*", "APF-Informed-RRT*"]

colors = {
    "RRT*": "#1f77b4",              # 藍色：baseline
    "Informed-RRT*": "#ff7f0e",     # 橘色：informed
    "APF-Informed-RRT*": "#2ca02c"  # 綠色：proposed
}

def add_labels(values):
    for i, v in enumerate(values):
        plt.text(i, v, f"{v:.2f}", ha="center", va="bottom", fontsize=9)

values = [stats[m]["node_count"] for m in methods]
plt.bar(methods, values, color=[colors[m] for m in methods])
add_labels(values)

plt.figure(figsize=(5,4))
plt.bar(
    methods,
    [stats[m]["node_count"] for m in methods],
    color=[colors[m] for m in methods]
)
plt.ylabel("Number of Nodes")
plt.title("Node Count Comparison")
plt.grid(axis="y", linestyle="--", alpha=0.6)
plt.show()

import matplotlib.pyplot as plt

methods = ["RRT*", "Informed-RRT*", "APF-Informed-RRT*"]

colors = {
    "RRT*": "#1f77b4",              # blue
    "Informed-RRT*": "#ff7f0e",     # orange
    "APF-Informed-RRT*": "#2ca02c"  # green
}

node_counts = [stats[m]["node_count"] for m in methods]
path_lengths = [stats[m]["path_length"] for m in methods]
times = [stats[m]["time"] for m in methods]

fig, axs = plt.subplots(1, 3, figsize=(15, 4))

# ---------- (a) Node count ----------
axs[0].bar(methods, node_counts,
           color=[colors[m] for m in methods])
axs[0].set_title("(a) Number of Nodes")
axs[0].set_ylabel("Nodes")
axs[0].grid(axis="y", linestyle="--", alpha=0.6)

for i, v in enumerate(node_counts):
    axs[0].text(i, v, f"{v}", ha="center", va="bottom", fontsize=9)

# ---------- (b) Path length ----------
axs[1].bar(methods, path_lengths,
           color=[colors[m] for m in methods])
axs[1].set_title("(b) Path Length")
axs[1].set_ylabel("Length")
axs[1].grid(axis="y", linestyle="--", alpha=0.6)

for i, v in enumerate(path_lengths):
    axs[1].text(i, v, f"{v:.2f}", ha="center", va="bottom", fontsize=9)

# ---------- (c) Computation time ----------
axs[2].bar(methods, times,
           color=[colors[m] for m in methods])
axs[2].set_title("(c) Computation Time")
axs[2].set_ylabel("Time (s)")
axs[2].grid(axis="y", linestyle="--", alpha=0.6)

for i, v in enumerate(times):
    axs[2].text(i, v, f"{v:.3f}", ha="center", va="bottom", fontsize=9)

plt.tight_layout()
plt.show()

plt.figure(figsize=(5,4))
plt.bar(
    methods,
    [stats[m]["path_length"] for m in methods],
    color=[colors[m] for m in methods]
)
plt.ylabel("Path Length")
plt.title("Path Length Comparison")
plt.grid(axis="y", linestyle="--", alpha=0.6)
plt.show()

plt.figure(figsize=(5,4))
plt.bar(
    methods,
    [stats[m]["time"] for m in methods],
    color=[colors[m] for m in methods]
)
plt.ylabel("Computation Time (s)")
plt.title("Computation Time Comparison")
plt.grid(axis="y", linestyle="--", alpha=0.6)
plt.show()